import pydbtools as pydb
import tempfile

def read_sql_query_py(sql: str, file_location: str) -> None:
  """Downloads the data frame generated by an SQL query and saves it as a 
  parquet file in a given location.
  This needs to be in a pure Python function to prevent reticulate calling a
  pandas dataframe conversion, which often fails in one way or another.
  
  Arguments:
    sql (str) -- An Athena SQL query
    file_location (str) -- The file location where the query result will be 
      saved
      
  Returns:
    None
  """
  
  df = pydb.read_sql_query(sql)
  df.to_parquet(file_location)

  return None


